In [57]:
arr1 = ['Pune',"Mumbai",'Surat',"Kolkata",'Bihar',"Jaipur",'Chennai']

In [58]:
type(arr1)

list

In [59]:
arr1[0]

'Pune'

In [60]:
import numpy
arr2 = numpy.array([10,20,30,40,50])

In [61]:
type(arr2)

numpy.ndarray

In [62]:
print(arr2)

[10 20 30 40 50]


In [63]:
arr2

array([10, 20, 30, 40, 50])

In [64]:
arr3 = numpy.array((100,200,300,400,500))

In [65]:
type(arr3)

numpy.ndarray

In [66]:
import numpy as np
a0 = np.array(10)

In [67]:
print(a0)

10


In [68]:
a0.ndim

0

In [69]:
a0

array(10)

In [70]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [71]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
a1.ndim

1

In [73]:
a2 = np.array([[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]])

In [74]:
a2

array([[   1,    2,    3],
       [  10,   20,   30],
       [ 100,  200,  300],
       [1000, 2000, 3000]])

In [75]:
a2.ndim

2

In [76]:
a3 = np.array([[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]])

In [77]:
a3

array([[[   1,    2,    3],
        [  10,   20,   30]],

       [[ 100,  200,  300],
        [1000, 2000, 3000]]])

In [78]:
a3.ndim

3

In [79]:
a4 = np.array([4,44,444,4444], ndmin=4)

In [80]:
a4

array([[[[   4,   44,  444, 4444]]]])

In [81]:
a4.ndim

4

In [82]:
arr2[1] # [10,20,30,40,50]

np.int64(20)

In [83]:
a2[1,2] # [[1,2,3],[10,20,30],[100,200,300],[1000,2000,3000]]

np.int64(30)

In [84]:
a2[2,2]

np.int64(300)

In [85]:
a3[0,0,0] # [[[1,2,3],[10,20,30]],[[100,200,300],[1000,2000,3000]]]

np.int64(1)

In [86]:
a4[0,0,0,3]

np.int64(4444)

In [87]:
a4[0,0,1,0] # at this index element is absent 

IndexError: index 1 is out of bounds for axis 2 with size 1

In [88]:
a12 = np.array([1,2,3])

In [90]:
a12[3] # at this index element is absent 

IndexError: index 3 is out of bounds for axis 0 with size 3

In [91]:
arrr = np.array((1,2,3,1,2,3,1,2,3))

In [92]:
arrr

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [93]:
arr2

array([10, 20, 30, 40, 50])

In [94]:
arr2[-1]

np.int64(50)

In [95]:
arr2[-2]

np.int64(40)

In [96]:
arr2[1:]

array([20, 30, 40, 50])

In [97]:
arr2[:3]

array([10, 20, 30])

In [98]:
arr2[:]

array([10, 20, 30, 40, 50])

In [99]:
arr2[0:4:1]

array([10, 20, 30, 40])

In [100]:
arr2[1:4:2]

array([20, 40])

In [101]:
arr2[:4:3]

array([10, 40])

In [102]:
arr2[::4]

array([10, 50])

In [103]:
arr2[::]

array([10, 20, 30, 40, 50])

In [104]:
for i in arr2:
  print(i)

10
20
30
40
50
